# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaK6CyCf1hGX9WZIydOEPvU9sZ7rk_KN
"""

import streamlit as st
import torch
from torchvision.utils import make_grid
import matplotlib.pyplot as plt
from cvae import CVAE, one_hot

st.set_page_config(page_title="Digit Generator", layout="centered")
st.title("MNIST Digit Generator")

device = torch.device("cpu")
model = CVAE().to(device)
model.load_state_dict(torch.load("cvae_mnist.pth", map_location=device))
model.eval()

digit = st.selectbox("Choose a digit (0–9)", list(range(10)))

if st.button("Generate Images"):
    y = torch.tensor([digit]*5)
    y_onehot = one_hot(y).to(device)
    z = torch.randn(5, 20)
    with torch.no_grad():
        images = model.decode(z, y_onehot).view(-1, 1, 28, 28)

    grid = make_grid(images, nrow=5, padding=2)
    plt.figure(figsize=(10, 2))
    plt.axis("off")
    plt.imshow(grid.permute(1, 2, 0).squeeze(), cmap="gray")
    st.pyplot(plt)